import 'dart:convert';

import 'package:build/build.dart';
import 'package:glob/glob.dart';

import 'document_assembler.dart';
import 'fragment.dart';
import 'fragment_builder.dart';
import 'openapi_options.dart';
import 'yaml_writer.dart';

/// Combines all `.openapi.json` fragments of the package into a single
/// OpenAPI 3.1 document written to the source tree.
class OpenApiBuilder implements Builder {
  final OpenApiOptions _options;

  OpenApiBuilder(this._options);

  @override
  Map<String, List<String>> get buildExtensions => {
    r'$package$': [_options.output],
  };

  static final _fragments = Glob('**${OpenApiFragmentBuilder.extension}');

  @override
  Future<void> build(BuildStep buildStep) async {
    final ids = await buildStep.findAssets(_fragments).toList()
      ..sort((a, b) => a.path.compareTo(b.path));
    final fragments = [
      for (final id in ids)
        ApiFragment.fromJson(
          jsonDecode(await buildStep.readAsString(id)) as Map<String, Object?>,
        ),
    ];
    final document = DocumentAssembler(_options).assemble(fragments);
    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package, _options.output),
      '# Generated by shelf_controller_generator. Do not edit by hand.\n'
      '${toYaml(document)}',
    );
  }
}
